### ISSUE TITLE
Delani studios website tasks to be completed.

### ISSUE THREAD

**Issue by Mwangik** [Mwangik/DelaniStudios#2]
# TODO
*Tasks/features to complete*
* [x] Header section-hero image with welcome text
* [x] About us section
* [x] Services section
* [x] What we do section
* [x] Portfolio section
* [x] Contact us section
* [x] Footer
* [x] Make website mobile responsive
:computer:  :point_up:
